In [1]:
import tensorflow as tf

In [2]:
# simple rnn (1)
# 
# 計算ルール： add_fn
# 入力値の並び： [1, 1, 1, 1, 1]
# 初期値： 0

def add_fn(h_tm1, x_t):
    return h_tm1 + x_t

x = tf.placeholder(dtype=tf.float32, shape=[None])
init_const1 = tf.constant(0., dtype=tf.float32)
h1 = tf.scan(add_fn, x, initializer=init_const1)

In [3]:
with tf.Session() as sess:
    fd = {x: [1, 1, 1, 1, 1]}
    results = sess.run(h1, feed_dict=fd)
    print(results)

[ 1.  2.  3.  4.  5.]


In [4]:
# simple rnn (2)
#
# 計算ルール： add_fn
# 入力値の並び： [1, 2, 3, 4, 5]
# 初期値： 0

init_const2 = tf.constant(0, dtype=tf.float32)
h2 = tf.scan(add_fn, x, initializer=init_const2)

In [5]:
with tf.Session() as sess:
    fd = {x: [1, 2, 3, 4, 5]}
    results = sess.run(h2, feed_dict=fd)
    print(results)

[  1.   3.   6.  10.  15.]


In [6]:
# simple rnn (3)
# 
# 計算ルール： mul_fn
# 入力値の並び： [1, 2, 3, 4, 5]
# 初期値： 1

def mul_fn(h_tm1, x_t):
    return h_tm1 * x_t

init_const3 = tf.constant(1, dtype=tf.float32)
h3 = tf.scan(mul_fn, x, initializer=init_const3)

In [7]:
with tf.Session() as sess:
    fd = {x: [1, 2, 3, 4, 5]}
    results = sess.run(h3, feed_dict=fd)
    print(results)

[   1.    2.    6.   24.  120.]


In [8]:
# simple rnn (4)
#
# 計算ルール： scalar_rec_fn
# 入力値の並び： [4, 2, 9, -1, 3]
# 初期値： 1

def scalar_rec_fn(h_tm1, x_t):
    return 2 * h_tm1 - 3 * x_t + 10

init_const4 = tf.constant(1, dtype=tf.float32)
h4 = tf.scan(scalar_rec_fn, x, initializer=init_const4)

In [9]:
with tf.Session() as sess:
    fd = {x: [4, 2, 9, -1, 3]}
    results = sess.run(h4, feed_dict=fd)
    print(results)

[ 0.  4. -9. -5. -9.]
